import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/page";
import MobileNav from "./components/Mobilenav/page";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/main.css" />
        <link rel="stylesheet" href="/assets/css/swiper/swiper.min.css" />
        <link rel="stylesheet" href="/assets/css/plugins/odometer/odometer-theme-default.css" />
        <link rel="stylesheet" href="/assets/css/header.css" />
        <link rel="stylesheet" href="/assets/css/section-heading.css" />
        <link rel="stylesheet" href="/assets/css/footer.css" />
        <link rel="stylesheet" href="/assets/css/style.css" />
        <link rel="stylesheet" href="/assets/css/seo-dark.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" crossOrigin="anonymous" referrerPolicy="no-referrer" />
        <link rel="stylesheet" href="/assets/css/shop.css" />
        <link rel="stylesheet" href="/assets/css/responsive.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} theme-style-social bg-23`}>
        <ToastContainer />
        <Navbar />
        <MobileNav />
        <div className="wrapper" >
          <div id="wptb-page-title-default" bis_skin_checked={1}>
            {/* <div
              className="wptb-page-title-default-bg"
              style={{
                backgroundImage:
                  "url(https://indiadhaniservice.co.in/frantend/img/background/bg-pagetitle.jpg)"
              }}
              bis_skin_checked={1}
            /> */}
            {/* <div className="container" bis_skin_checked={1}>
              <div className="row" bis_skin_checked={1}>
                <div className="col-12" bis_skin_checked={1}>
                  <h1 className="wptb-page-title">Company Profile</h1>
                </div>
              </div>
            </div> */}
          </div>
          {children}
        </div>

        {/* <!-- Core JS --> */}
        <script src="/assets/js/jquery-3.6.0.min.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>

        {/* <!-- Swiper Slider --> */}
        <script src="/assets/js/plugins/swiper/swiper-bundle.min.js"></script>

        {/* <!-- Odometer --> */}
        <script src="/assets/js/plugins/odometer/appear.js"></script>
        <script src="/assets/js/plugins/odometer/odometer.js"></script>

        {/* <!-- Split Text --> */}
        {/* <!-- <script src="plugins/splittext/splt.min.js"></script> */}
        <script src="plugins/anime/anime.min.js"></script>

        {/* <!-- WOW Effect --> */}
        <script src="/assets/js/plugins/wow/wow.min.js"></script>
        {/* <!-- <script src="/assets/js/cursor.js"></script> --> */}

        {/* <!-- Theme Custom JS --> */}
        <script src="/assets/js/theme.js"></script>

        <script src="/assets/js/jquery-3.6.0.min.js"></script>
        <script src="/assets/js/swiper/swiper.min.js"></script>
        {/* <script src="/assets/js/functions.js"></script> */}

      </body>
    </html>
  );
}
